
variable_name:
min_length: # not possible to disable this partial rule, so set it to zero
warning_threshold: 30
error: 0
line_length:
 warning: 220
disabled_rules:
  - trailing_whitespace
excluded:
  — Pods
opt_in_rules:
  - force_unwrapping
