
variable_name:
min_length: # not possible to disable this partial rule, so set it to zero
warning_threshold: 15
error: 0
line_length:
 warning: 200
disabled_rules:
 — trailing_whitespace
 - line_length
